"""updated modules

Revision ID: 566b71d8c14c
Revises: d5ac636c3bce
Create Date: 2025-06-24 11:51:42.776067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566b71d8c14c'
down_revision = 'd5ac636c3bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('specialty')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
