"""Add site_setting table

Revision ID: a7199d3c092c
Revises: cf8c5f7e5f6e
Create Date: 2025-07-06 20:04:42.076506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7199d3c092c'
down_revision = 'cf8c5f7e5f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_setting')
    # ### end Alembic commands ###
