"""Update employee payment fields

Revision ID: b64d3c3a631e
Revises: 566b71d8c14c
Create Date: 2025-06-25 10:43:59.590882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64d3c3a631e'
down_revision = '566b71d8c14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rate_unit', sa.String(length=50), nullable=True))
        batch_op.drop_column('expected_salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_salary', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('rate_unit')
        batch_op.drop_column('expected_rate')

    # ### end Alembic commands ###
